workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1

workflows:
    build-android:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        scripts:
          - name: Set up local properties # required for Android build
            script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          - name: Build Android debug     # for building in debug mode
            script: flutter build apk --debug
